// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrpryuklixnggykocclh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycHJ5dWtsaXhuZ2d5a29jY2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjAxMDAsImV4cCI6MjA3MzU5NjEwMH0.QhnQDQZBoQX12CGi1qMc63bqWIHaCjZmir8-bNPL1Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});